default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: 5
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: test_deploy

test:
  <<: *default
  database: test_deploy

staging:
  <<: *default
  database: test_deploy